---
name: App-PNGCrush
version: 0.001
author:
  - 'Zoffix Znet <zoffix@cpan.org>'
abstract: Perl wrapper around ``pngcrush'' program
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 1.04
  Class::Data::Accessor: 0.04001
  Devel::TakeHashArgs: 0.003
  Proc::Reliable: 1.16
build_requires:
  Test::More: 0
provides:
  App::PNGCrush:
    file: lib/App/PNGCrush.pm
    version: 0.001
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
